# 暴涨做空策略配置文件 / Pump Short Strategy Configuration
# ================================================
# 
# 本配置文件包含暴涨做空策略的所有可配置参数
# This configuration file contains all configurable parameters for the pump short strategy
#
# 配置分类 / Configuration Categories:
# 1. 策略核心参数 / Strategy Core Parameters
# 2. 风险管理参数 / Risk Management Parameters  
# 3. 执行器参数 / Executor Parameters
# 4. 投资组合参数 / Portfolio Parameters
# 5. 数据处理参数 / Data Processing Parameters

# ====================================
# 策略核心参数 / Strategy Core Parameters
# ====================================
strategy:
  # 暴涨识别参数 / Pump Detection Parameters
  pump_threshold: 0.8          # 暴涨阈值80% / Pump threshold 80%
  lookback_days: 3             # 回望天数3天 / Lookback period 3 days
  
  # 加仓控制参数 / Add Position Control Parameters
  add_up_threshold: 0.1        # 上涨加仓阈值10% / Add on up threshold 10%
  add_down_threshold: 0.065    # 下跌加仓阈值6.5% / Add on down threshold 6.5%
  max_add_times: 3             # 最大加仓次数3次 / Max add times 3
  
  # 止盈止损参数 / Take Profit & Stop Loss Parameters
  stop_loss_threshold: 0.35    # 止损阈值35% / Stop loss threshold 35%
  take_profit_threshold: 0.12  # 止盈阈值12% / Take profit threshold 12%
  
  # 技术指标参数 / Technical Indicator Parameters
  volume_multiplier: 1.5       # 成交量倍数1.5倍 / Volume multiplier 1.5x
  upper_shadow_ratio: 0.3      # 上影线比例30% / Upper shadow ratio 30%

# ====================================
# 风险管理参数 / Risk Management Parameters
# ====================================
risk_management:
  # 单持仓风险限制 / Single Position Risk Limits
  max_position_size_ratio: 0.1     # 单个持仓最大资金比例10% / Max single position ratio 10%
  single_position_max_loss_ratio: 0.05  # 单持仓最大亏损5% / Single position max loss 5%
  
  # 组合级风险限制 / Portfolio Level Risk Limits
  max_total_exposure_ratio: 0.8    # 总敞口最大比例80% / Max total exposure ratio 80%
  portfolio_stop_loss_ratio: 0.15  # 组合止损比例15% / Portfolio stop loss ratio 15%
  
  # 持仓数量限制 / Position Count Limits
  max_concurrent_positions: 5      # 最大同时持仓数5个 / Max concurrent positions 5
  max_correlation_positions: 3     # 最大相关性持仓数3个 / Max correlated positions 3

# ====================================
# 执行器参数 / Executor Parameters
# ====================================
executor:
  # 信号过滤参数 / Signal Filter Parameters
  min_signal_strength: 0.6        # 最小信号强度0.6 / Minimum signal strength 0.6
  default_position_size_ratio: 0.08  # 默认仓位大小比例8% / Default position size ratio 8%
  
  # 自动执行开关 / Auto Execution Switches
  enable_add_positions: true       # 启用加仓功能 / Enable add positions
  enable_auto_stop_loss: true      # 启用自动止损 / Enable auto stop loss
  enable_auto_take_profit: true    # 启用自动止盈 / Enable auto take profit
  
  # 监控参数 / Monitoring Parameters
  check_interval: 60               # 检查间隔60秒 / Check interval 60 seconds
  price_update_threshold: 0.001    # 价格更新阈值0.1% / Price update threshold 0.1%

# ====================================
# 投资组合参数 / Portfolio Parameters
# ====================================
portfolio:
  # 初始设置 / Initial Settings
  initial_capital: 10000.0         # 初始资金$10,000 / Initial capital $10,000
  
  # 交易成本 / Trading Costs
  fee_rate: 0.001                  # 手续费率0.1% / Fee rate 0.1%
  slippage_rate: 0.0005            # 滑点率0.05% / Slippage rate 0.05%
  
  # 现金管理 / Cash Management
  min_cash_ratio: 0.1              # 最小现金比例10% / Minimum cash ratio 10%
  max_leverage: 1.0                # 最大杠杆倍数1倍（无杠杆）/ Max leverage 1x (no leverage)

# ====================================
# 数据处理参数 / Data Processing Parameters
# ====================================
data:
  # K线数据格式 / Candlestick Data Format
  required_columns:                # 必需的数据列 / Required data columns
    - "timestamp"                  # 时间戳 / Timestamp
    - "open"                       # 开盘价 / Open price
    - "high"                       # 最高价 / High price
    - "low"                        # 最低价 / Low price
    - "close"                      # 收盘价 / Close price
    - "volume"                     # 成交量 / Volume
  
  # 数据验证参数 / Data Validation Parameters
  min_data_points: 10              # 最少数据点数10个 / Minimum data points 10
  max_price_change: 10.0           # 最大单日涨跌幅限制1000% / Max daily price change 1000%
  min_volume: 1.0                  # 最小成交量1 / Minimum volume 1
  
  # 数据处理选项 / Data Processing Options
  fill_missing_data: true          # 填补缺失数据 / Fill missing data 
  remove_outliers: true            # 移除异常值 / Remove outliers
  normalize_volume: false          # 标准化成交量 / Normalize volume

# ====================================
# 回测参数 / Backtesting Parameters
# ====================================
backtest:
  # 回测时间范围 / Backtest Time Range
  start_date: "2024-01-01"         # 开始日期 / Start date
  end_date: "2024-12-31"           # 结束日期 / End date
  
  # 数据来源 / Data Source
  data_source: "csv"               # 数据来源类型 / Data source type
  data_file: "data/sample_kline.csv"  # 数据文件路径 / Data file path
  
  # 回测选项 / Backtest Options
  benchmark_symbol: "BTC"          # 基准标的 / Benchmark symbol
  calculate_metrics: true          # 计算性能指标 / Calculate performance metrics
  export_results: true             # 导出结果 / Export results
  
  # 结果输出 / Result Output
  results_dir: "results"           # 结果目录 / Results directory
  export_trades: true              # 导出交易记录 / Export trade records
  export_positions: true           # 导出持仓记录 / Export position records
  generate_charts: false           # 生成图表（需要matplotlib）/ Generate charts (requires matplotlib)

# ====================================
# 日志配置 / Logging Configuration
# ====================================
logging:
  # 日志级别 / Log Level
  level: "INFO"                    # 日志级别: DEBUG, INFO, WARNING, ERROR / Log level
  
  # 日志输出 / Log Output
  console_output: true             # 控制台输出 / Console output
  file_output: true                # 文件输出 / File output
  log_file: "logs/strategy.log"    # 日志文件路径 / Log file path
  
  # 日志格式 / Log Format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # 日志轮转 / Log Rotation
  max_file_size: "10MB"            # 最大文件大小 / Max file size
  backup_count: 5                  # 备份数量 / Backup count

# ====================================
# 高级设置 / Advanced Settings
# ====================================
advanced:
  # 性能优化 / Performance Optimization
  enable_multiprocessing: false    # 启用多进程（实验性）/ Enable multiprocessing (experimental)
  max_workers: 4                   # 最大工作进程数 / Max worker processes
  
  # 调试选项 / Debug Options
  debug_mode: false                # 调试模式 / Debug mode
  save_intermediate_data: false    # 保存中间数据 / Save intermediate data
  verbose_logging: false           # 详细日志 / Verbose logging
  
  # 扩展功能 / Extended Features
  enable_web_api: false            # 启用Web API（未实现）/ Enable Web API (not implemented)
  enable_telegram_bot: false       # 启用Telegram机器人（未实现）/ Enable Telegram bot (not implemented)
  enable_email_alerts: false       # 启用邮件提醒（未实现）/ Enable email alerts (not implemented)

# ====================================
# 环境特定配置 / Environment Specific Configuration
# ====================================
# 开发环境 / Development Environment
development:
  initial_capital: 1000.0          # 开发环境初始资金 / Dev initial capital
  debug_mode: true                 # 开启调试模式 / Enable debug mode
  verbose_logging: true            # 详细日志 / Verbose logging

# 测试环境 / Testing Environment  
testing:
  initial_capital: 5000.0          # 测试环境初始资金 / Test initial capital
  max_concurrent_positions: 3      # 限制持仓数 / Limit positions
  enable_all_features: true        # 启用所有功能测试 / Enable all features for testing

# 生产环境 / Production Environment
production:
  initial_capital: 50000.0         # 生产环境初始资金 / Prod initial capital
  strict_risk_management: true     # 严格风险管理 / Strict risk management
  enable_all_alerts: true          # 启用所有提醒 / Enable all alerts
  conservative_settings: true      # 保守设置 / Conservative settings 